image: maven:latest

# 本次构建的阶段：build package
stages:
- build
- package
- deploy
# 构建 Job
build:
  stage: build
  tags:
  - win10
  script:
  - echo "=============== 开始编译构建任务 ==============="
  - mvn compile
# 打包
package:
  stage: package
  tags:
  - win10
  script:
  - echo "=============== 开始打包任务  ==============="
  - mvn package -Dmaven.test.skip=true
# 部署
deploy:
  stage: deploy
  tags:
  - win10
  script:
    - echo "=============== 开始部署任务  ==============="
    # - java -jar target\cicdd-0.0.1-SNAPSHOT.jar
    - cd target
    - docker build -t cicdd .
    - docker run -d -p 8888:8080 --name cicdd-democ cicdd
