image: maven:3-jdk-8

cache:
  paths:
    - ./.m2/repository
  key: "$CI_BUILD_REF_NAME"

    # 本次构建的阶段：build package
stages:
  - build
  - package
  - deploy
# 构建 Job
build:
  stage: build
  tags:
    - win10
  script:
    - echo "=============== 开始编译构建任务 ==============="
    - mvn compile
# 打包
package:
  stage: package
  tags:
    - win10
  script:
    - echo "=============== 开始打包任务  ==============="
    - mvn package -Dmaven.test.skip=true

# 部署
deploy:
  stage: deploy
  tags:
    - win10
  script:
    - echo "=============== 开始部署任务  ==============="
    # 删除已经在运行的容器
    - if [ $(docker ps -aq --filter name= cicdd-democ) ]; then docker rm -f cicdd-democ;fi
    # 删除已经存在的镜像
    - if [ $(docker images --filter name= cicdd) ]; then docker rmi -f cicdd;fi
    # 编译镜像
    - docker build -t cicdd ./target
    # 运行容器
    - docker run -d -p 8888:8080 --name cicdd-democ cicdd
  artifacts:
    paths:
      - target/