# 设置 Maven 阿里云镜像 也可以在 /root/.m2 目录中编辑 settings.xml文件 添加阿里云镜像信息
before_script:
  - rm -rf /root/.m2/settings.xml
  - echo -e "<?xml version=\""1.0\"" encoding=\""UTF-8\""?><settings xmlns=\""http://maven.apache.org/SETTINGS/1.0.0\"" xmlns:xsi=\""http://www.w3.org/2001/XMLSchema-instance\"" xsi:schemaLocation=\""http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd\""><mirrors><mirror><id>alimaven</id><name>aliyun maven</name><url>http://maven.aliyun.com/nexus/content/groups/public/</url><mirrorOf>central</mirrorOf></mirror></mirrors></settings>"> /root/.m2/settings.xml

# 使用docker最新镜像
image: docker:latest

# 定义job执行使用的环境变量
variables:
  DOCKER_DRIVER: overlay2
  # DOCKER_HOST: tcp://192.168.2.132:2375  # docker host，本地可不写
  # 镜像名称
  TAG: cicdd-v1.0.0
  # 容器名称
  CONTAINER_NAME: hello-cicd
  PORT: 8765

# 配置缓存，缓存maven下载的依赖
cache:
  paths:
    - .m2/repository

# 配置需要用到的额外的服务。docker:dind，用于在 docker 中运行 docker 的一种东西，在项目的构建中需要。    
services:
  - docker:dind

stages:
  - package
  - deploy

# 定义的 Jobs 之一，用于构建 jar 包。内部又引入 maven 镜像来处理，负责执行 package 这一流程。 
maven-package:
  image: maven:3.6.3-jdk-8
  tags:
    - tiny
  stage: package
  script:
    - mvn clean package -Dmaven.test.skip=true
  # 定义哪些文件需要在下一个job使用
  artifacts:
    paths:
      - target/*.jar

# 定义的 Jobs 之一，用于构建 Docker 镜像。负责执行 deploy 这一流程。具体执行 build 和 run。
build-master:
  tags:
    - tiny
  stage: deploy
  script:
    # 构件镜像
    - docker build -t $TAG -f /target/Dockerfile .
    # 删除容器
    - docker rm -f $CONTAINER_NAME || true
    # 运行容器
    - docker run -d --name $CONTAINER_NAME -p $PORT:8080 $TAG
  only:
    - master